### ISSUE TITLE
Mod crashes on 1.19

### ISSUE THREAD

**Issue by BookWyrm114** [Declipsonator/Particle-Blocker#4]
![image](https://user-images.githubusercontent.com/79489385/172967725-c6cd2318-37ba-49e2-9095-a749674ee395.png)
[latest.log](https://github.com/Declipsonator/Particle-Blocker/files/8874884/latest.log)

**Comment by Declipsonator** [comment]
1.19 has been released on modrinth, awaiting curseforge to approve.
