### ISSUE TITLE
Update? 

### ISSUE THREAD

**Issue by blade5280** [Declipsonator/Particle-Blocker#7]
Is there goin to be a 1.19.3 update?

**Comment by Declipsonator** [comment]
Does it crash on 1.19.3?

**Comment by blade5280** [comment]
Yes it does.

**Comment by Declipsonator** [comment]
Ok, I'll get working on it

**Comment by blade5280** [comment]
Thank you and thanks for the fast reply

**Comment by Declipsonator** [comment]
I just happened to be online when you made the issue lol

**Comment by Declipsonator** [comment]
It's updated now, the file is on modrinth and will appear on curseforge once it is approved.
